### ISSUE TITLE
Doesn't work on Mac

### ISSUE THREAD

**Issue by Imzxhir** [Gaming32/mod-loading-screen#1]
Mod Version: 1.0.0
Mod Loader: Quilt
Loader Version: 0.17.10
Logs: https://mclo.gs/wvldDFN

Description: The mod loading screen doesn't show or pop up after it says opening loading screen, also I get stuck on a black screen after the Minecraft Window has popped up.

Screenshots: 
![image](https://user-images.githubusercontent.com/98621617/213908887-a5912224-f71e-4434-84fc-53eea7e9f095.png)

**Comment by Gaming32** [comment]
This looks like Mac. AWT has... issues on Mac. Since I don't really have a Mac that's not a [potato](https://i1.theportalwiki.net/img/5/58/GLaDOS_potatos_longfall_speech03.wav), I didn't test it. But since there's someone who has a Mac, I'll see about getting it to work on Mac.

**Comment by Gaming32** [comment]
...and it breaks on Quilt
