### ISSUE TITLE
Cant launch minecraft on 1.20 quilt

### ISSUE THREAD

**Issue by Rozbiynk** [Gaming32/mod-loading-screen#14]
https://mclo.gs/lDTaHJR - latest log
https://mclo.gs/bRZ12ZX - crash report

**Comment by Gaming32** [comment]
This bug has already been fixed.

**Comment by Rozbiynk** [comment]
bro im using 1.0.1...

**Comment by Rozbiynk** [comment]
oh i see it an actions, sorry
