### ISSUE TITLE
[Suggestion] Provide a stable api for mods which wants to add their own entrypoint progress bar

### ISSUE THREAD

**Issue by thecatcore** [Gaming32/mod-loading-screen#15]

**Comment by Gaming32** [comment]
If you use Quilt, there is an API for you. If you don't, there's not really a good way for me to add one, because of ClassLoader stuff.

**Comment by Gaming32** [comment]
This is now available in the latest published release. It includes an API for you to run entrypoints (and is a lot cleaner to use than what you normally use too!).
