### ISSUE TITLE
1.20.6 Update

### ISSUE THREAD

**Issue by bruh1273** [Gaming32/mod-loading-screen#26]
This is by far (in my humble opinion) the most _underrated_ mod to ever exist. Please consider updating to latest; 1.20.6.
Thank you so much!

**Comment by Gaming32** [comment]
This mod should already work without issue on 1.20.6, as it doesn't even require Minecraft in the first place.

**Comment by Gaming32** [comment]
Updated the information on Modrinth to reflect this.
