### ISSUE TITLE
Stuck after Loading window finishes

### ISSUE THREAD

**Issue by SaviorD22** [Gaming32/mod-loading-screen#29]
Im able to get the loading window on macos, and it finishes correctly, but then when minecraft actually starts, its stuck and doesnt open, the icon stays saying "not responding".  The weird thing is that without the loading window mod the modpack actually loads, and testing the window loading mod alone makes minecraft open, so I bet its a mod that causes a conflict somehow.  I will leave the logs just in case.

[latest.log](https://github.com/user-attachments/files/16768499/latest.log)

It looks as if it was halfways there but the problem is, that the cpu usage is usually high during the startup, with window loading mod, the cpu stays high for a bit and then drastically drops and now minecraft is using almost no cpu and cannot continue initializing the game.  Remember that without this mod the game opens perfectly, so it may be a mod compatibility or the mod itself.

**Comment by Gaming32** [comment]
Can you upload the `ipc-client-log.txt` file from the `.cache/mod-loading-screen` folder inside your instance folder?

**Comment by SaviorD22** [comment]
fixed, removing craft-pressence solves the issue

**Comment by SaviorD22** [comment]
btw I renamed background.gif to background.png and I all see is a gray background when opening the game, am I doing something wrong?

**Comment by Gaming32** [comment]
Can you upload a log with your launcher's built-in upload log functionality (if it has one)?

**Comment by SaviorD22** [comment]
[ipc-client-log.txt](https://github.com/user-attachments/files/16769557/ipc-client-log.txt)

**Comment by SaviorD22** [comment]
The game loads fine with the cpu being high, but when getting to this point, the game refuses to fully start.

<img width="1002" alt="Screenshot 2024-08-27 at 3 06 37 p m" src="https://github.com/user-attachments/assets/490f8ac4-b262-4ff7-a220-cae10fcf9d7f">

**Comment by Gaming32** [comment]
What modpack are you using? I want to try to repro.

**Comment by SaviorD22** [comment]
Modrinth doesnt let me upload .mrpack so I zipped it
CoreCraft Reimagined 1.0.0.mrpack.zip](https://github.com/user-attachments/files/16769653/CoreCraft.Reimagined.1.0.0.mrpack.zip)

**Comment by SaviorD22** [comment]
Apparently I cant enter to the game's main loop.

This is the log without the mod

<img width="1001" alt="Screenshot 2024-08-27 at 3 18 21 p m" src="https://github.com/user-attachments/assets/6fb5fbe2-26ed-40e9-8037-03a301930747">

**Comment by SaviorD22** [comment]
Do you get the same output?
