### ISSUE TITLE
X Error of failed request:  RenderBadPicture (invalid Picture parameter) (Kubuntu 22.10, MultiMC, MC 1.19.2, Quilt)

### ISSUE THREAD

**Issue by retropele** [Gaming32/mod-loading-screen#7]
As in title, I'm getting this error - went through all mods and this is the one that initiates the error. It causes my Quilt installation to quit out just before we get into the Title screen. Also seems attributed to Iris, is there an incompatibility?

I'm an amateur, error seems commonly associated with the X system for Linux and some potentially historical bugs in Java.

Kubuntu 22.10
Quilt loader 1.18.3
Minecraft 1.19.2

Java --version outputs:
openjdk 17.0.6 2023-01-17
OpenJDK Runtime Environment (build 17.0.6+10-Ubuntu-0ubuntu122.10)
OpenJDK 64-Bit Server VM (build 17.0.6+10-Ubuntu-0ubuntu122.10, mixed mode, sharing)

[crashlog.txt](https://github.com/Gaming32/mod-loading-screen/files/10892853/crashlog.txt)

**Comment by Gaming32** [comment]
Does this happen without the Mod Loading Screen? Does it happen with other Java GUI applications?

**Comment by retropele** [comment]
It does not happen with other mods, I went through and added all one by one - its specific to mod loading screen. I did remove some mods and mod loading screen still halted the game. I'll try it on its own now and see if it happens when loading alone.

As regards the java GUI applications, I haven't encountered it but don't have any other applications that require Java to my knowledge. If there's one you know of (that I can run on Kubunto 22.10) I can install and test.

-------- Original Message --------

**Comment by retropele** [comment]
I still got the crash when running it completely solo. It did however boot into the red Mojang loading page this time for a second or two before the crash.

Here's the log:

solomodloadingtestcrash.txt](https://github.com/Gaming32/mod-loading-screen/files/10893147/solomodloadingtestcrash.txt)

**Comment by retropele** [comment]
Removing my custom java arguments fixed the problem completely. These are the arguments I used:

-XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1

I still had MultiMC's minimum + maximum memory allocation set to 5300MB for both however and it didn't affect it.

I'm too inexperienced to narrow it down any further to which one it is, but if I could know I would love to be able to change it so I could keep these/some of these and use this mod.

**Comment by LastExceed** [comment]
a few observations:
## this is linux specific
i have extensively tested 4 different systems (win11, win10, manjaro, steamOS), and it only occurrs on the latter two

## this doesn't always happen
on a few occasions i have managed to successfully boot and play the game with this mod enabled, and then on a re-run (with literally nothing changed) it crashed

## it seems to be more likely to happen with lots of mods installed
i have a total of 99 mods installed on my steamdeck, one of them being this one
* with all 99 mods enabled it crashes about 80% of the time
* with just sodium, iris, and this mod, i've only managed to reproduce this crash once in 10 attempts
* with just this mod and nothing else i haven't been able to reproduce this crash at all
* withOUT this mod and all other 98 mods enabled this crash has never occurred, so i'm still confident that this mod is (at least partially) at fault

hope this helps

**Comment by Gaming32** [comment]
Try passing `-Dmod-loading-screen.enableIpc=true` as a JVM arg, and see if that helps.

**Comment by xyxt1c** [comment]
I had the exact same x server problem as the author on Linux Mint using GraalVM (ee-java17-22.3.1) with full optimizations described in [https://github.com/brucethemoose/Minecraft-Performance-Flags-Benchmarks](https://github.com/brucethemoose/Minecraft-Performance-Flags-Benchmarks).

Just adding `-Dmod-loading-screen.enableIpc=true` to the parameters fixed the issue in my case.

**Comment by Geldra** [comment]
Adding to the workaround confirmation: `-Dmod-loading-screen.enableIpc=true` works on 1.20.1 / Fabric / Manjaro

**Comment by MaxenceDC** [comment]
Encountered the same issue on EndeavourOS, eventually found the cause, and using `-Dmod-loading-screen.enableIpc=true` fixed it for me too. 
I would love to know why this work and why it's not enabled by default, because it would have saved me so much time!
Thx for the fix and your mod btw!

**Comment by MaxenceDC** [comment]
@Gaming32 ?

**Comment by Gaming32** [comment]
Yeah, I'm planning on making improvements soon.
